'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl", ConfigurationName:="ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType")>  _
    Public Interface ndfdXMLPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgen", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function NDFDgen(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal product As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.productType, ByVal startTime As Date, ByVal endTime As Date, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As <System.ServiceModel.MessageParameterAttribute(Name:="dwmlOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDay", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function NDFDgenByDay(ByVal latitude As Decimal, ByVal longitude As Decimal, <System.Xml.Serialization.SoapElementAttribute(DataType:="date")> ByVal startDate As Date, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal numDays As String, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal format As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.formatType) As <System.ServiceModel.MessageParameterAttribute(Name:="dwmlByDayOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenLatLonList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function NDFDgenLatLonList(ByVal listLatLon As String, ByVal product As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.productType, ByVal startTime As Date, ByVal endTime As Date, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As <System.ServiceModel.MessageParameterAttribute(Name:="dwmlOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#NDFDgenByDayLatLonList"& _ 
            "", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function NDFDgenByDayLatLonList(ByVal listLatLon As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="date")> ByVal startDate As Date, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal numDays As String, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal format As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.formatType) As <System.ServiceModel.MessageParameterAttribute(Name:="dwmlByDayOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlLatLonList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function GmlLatLonList(ByVal listLatLon As String, ByVal requestedTime As Date, ByVal featureType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.featureTypeType, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As <System.ServiceModel.MessageParameterAttribute(Name:="dwGmlOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#GmlTimeSeries", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function GmlTimeSeries(ByVal listLatLon As String, ByVal startTime As Date, ByVal endTime As Date, ByVal compType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.compTypeType, ByVal featureType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.featureTypeType, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal propertyName As String) As <System.ServiceModel.MessageParameterAttribute(Name:="dwGmlOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSubgrid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function LatLonListSubgrid(ByVal lowerLeftLatitude As Decimal, ByVal lowerLeftLongitude As Decimal, ByVal upperRightLatitude As Decimal, ByVal upperRightLongitude As Decimal, ByVal resolution As Decimal) As <System.ServiceModel.MessageParameterAttribute(Name:="listLatLonOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListLine", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function LatLonListLine(ByVal endPoint1Lat As Decimal, ByVal endPoint1Lon As Decimal, ByVal endPoint2Lat As Decimal, ByVal endPoint2Lon As Decimal) As <System.ServiceModel.MessageParameterAttribute(Name:="listLatLonOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function LatLonListZipCode(ByVal zipCodeList As String) As <System.ServiceModel.MessageParameterAttribute(Name:="listLatLonOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListSquare", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function LatLonListSquare(ByVal centerPointLat As Decimal, ByVal centerPointLon As Decimal, ByVal distanceLat As Decimal, ByVal distanceLon As Decimal, ByVal resolution As Decimal) As <System.ServiceModel.MessageParameterAttribute(Name:="listLatLonOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#CornerPoints", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function CornerPoints(ByVal sector As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.sectorType) As <System.ServiceModel.MessageParameterAttribute(Name:="listLatLonOut")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListCityNames", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function LatLonListCityNames(<System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal displayLevel As String) As <System.ServiceModel.MessageParameterAttribute(Name:="listCityNamesOut")> String
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum productType
        
        '''<remarks/>
        <System.Xml.Serialization.SoapEnumAttribute("time-series")>  _
        timeseries
        
        '''<remarks/>
        glance
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum unitType
        
        '''<remarks/>
        e
        
        '''<remarks/>
        m
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Partial Public Class weatherParametersType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private maxtField As Boolean
        
        Private mintField As Boolean
        
        Private tempField As Boolean
        
        Private dewField As Boolean
        
        Private pop12Field As Boolean
        
        Private qpfField As Boolean
        
        Private skyField As Boolean
        
        Private snowField As Boolean
        
        Private wspdField As Boolean
        
        Private wdirField As Boolean
        
        Private wxField As Boolean
        
        Private wavehField As Boolean
        
        Private iconsField As Boolean
        
        Private rhField As Boolean
        
        Private apptField As Boolean
        
        Private incw34Field As Boolean
        
        Private incw50Field As Boolean
        
        Private incw64Field As Boolean
        
        Private cumw34Field As Boolean
        
        Private cumw50Field As Boolean
        
        Private cumw64Field As Boolean
        
        Private critfireoField As Boolean
        
        Private dryfireoField As Boolean
        
        Private conhazoField As Boolean
        
        Private ptornadoField As Boolean
        
        Private phailField As Boolean
        
        Private ptstmwindsField As Boolean
        
        Private pxtornadoField As Boolean
        
        Private pxhailField As Boolean
        
        Private pxtstmwindsField As Boolean
        
        Private ptotsvrtstmField As Boolean
        
        Private pxtotsvrtstmField As Boolean
        
        Private tmpabv14dField As Boolean
        
        Private tmpblw14dField As Boolean
        
        Private tmpabv30dField As Boolean
        
        Private tmpblw30dField As Boolean
        
        Private tmpabv90dField As Boolean
        
        Private tmpblw90dField As Boolean
        
        Private prcpabv14dField As Boolean
        
        Private prcpblw14dField As Boolean
        
        Private prcpabv30dField As Boolean
        
        Private prcpblw30dField As Boolean
        
        Private prcpabv90dField As Boolean
        
        Private prcpblw90dField As Boolean
        
        Private precipa_rField As Boolean
        
        Private sky_rField As Boolean
        
        Private td_rField As Boolean
        
        Private temp_rField As Boolean
        
        Private wdir_rField As Boolean
        
        Private wspd_rField As Boolean
        
        Private wwaField As Boolean
        
        Private tstmprbField As Boolean
        
        Private tstmcatField As Boolean
        
        Private wgustField As Boolean
        
        Private iceaccumField As Boolean
        
        '''<remarks/>
        Public Property maxt() As Boolean
            Get
                Return Me.maxtField
            End Get
            Set
                Me.maxtField = value
                Me.RaisePropertyChanged("maxt")
            End Set
        End Property
        
        '''<remarks/>
        Public Property mint() As Boolean
            Get
                Return Me.mintField
            End Get
            Set
                Me.mintField = value
                Me.RaisePropertyChanged("mint")
            End Set
        End Property
        
        '''<remarks/>
        Public Property temp() As Boolean
            Get
                Return Me.tempField
            End Get
            Set
                Me.tempField = value
                Me.RaisePropertyChanged("temp")
            End Set
        End Property
        
        '''<remarks/>
        Public Property dew() As Boolean
            Get
                Return Me.dewField
            End Get
            Set
                Me.dewField = value
                Me.RaisePropertyChanged("dew")
            End Set
        End Property
        
        '''<remarks/>
        Public Property pop12() As Boolean
            Get
                Return Me.pop12Field
            End Get
            Set
                Me.pop12Field = value
                Me.RaisePropertyChanged("pop12")
            End Set
        End Property
        
        '''<remarks/>
        Public Property qpf() As Boolean
            Get
                Return Me.qpfField
            End Get
            Set
                Me.qpfField = value
                Me.RaisePropertyChanged("qpf")
            End Set
        End Property
        
        '''<remarks/>
        Public Property sky() As Boolean
            Get
                Return Me.skyField
            End Get
            Set
                Me.skyField = value
                Me.RaisePropertyChanged("sky")
            End Set
        End Property
        
        '''<remarks/>
        Public Property snow() As Boolean
            Get
                Return Me.snowField
            End Get
            Set
                Me.snowField = value
                Me.RaisePropertyChanged("snow")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wspd() As Boolean
            Get
                Return Me.wspdField
            End Get
            Set
                Me.wspdField = value
                Me.RaisePropertyChanged("wspd")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wdir() As Boolean
            Get
                Return Me.wdirField
            End Get
            Set
                Me.wdirField = value
                Me.RaisePropertyChanged("wdir")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wx() As Boolean
            Get
                Return Me.wxField
            End Get
            Set
                Me.wxField = value
                Me.RaisePropertyChanged("wx")
            End Set
        End Property
        
        '''<remarks/>
        Public Property waveh() As Boolean
            Get
                Return Me.wavehField
            End Get
            Set
                Me.wavehField = value
                Me.RaisePropertyChanged("waveh")
            End Set
        End Property
        
        '''<remarks/>
        Public Property icons() As Boolean
            Get
                Return Me.iconsField
            End Get
            Set
                Me.iconsField = value
                Me.RaisePropertyChanged("icons")
            End Set
        End Property
        
        '''<remarks/>
        Public Property rh() As Boolean
            Get
                Return Me.rhField
            End Get
            Set
                Me.rhField = value
                Me.RaisePropertyChanged("rh")
            End Set
        End Property
        
        '''<remarks/>
        Public Property appt() As Boolean
            Get
                Return Me.apptField
            End Get
            Set
                Me.apptField = value
                Me.RaisePropertyChanged("appt")
            End Set
        End Property
        
        '''<remarks/>
        Public Property incw34() As Boolean
            Get
                Return Me.incw34Field
            End Get
            Set
                Me.incw34Field = value
                Me.RaisePropertyChanged("incw34")
            End Set
        End Property
        
        '''<remarks/>
        Public Property incw50() As Boolean
            Get
                Return Me.incw50Field
            End Get
            Set
                Me.incw50Field = value
                Me.RaisePropertyChanged("incw50")
            End Set
        End Property
        
        '''<remarks/>
        Public Property incw64() As Boolean
            Get
                Return Me.incw64Field
            End Get
            Set
                Me.incw64Field = value
                Me.RaisePropertyChanged("incw64")
            End Set
        End Property
        
        '''<remarks/>
        Public Property cumw34() As Boolean
            Get
                Return Me.cumw34Field
            End Get
            Set
                Me.cumw34Field = value
                Me.RaisePropertyChanged("cumw34")
            End Set
        End Property
        
        '''<remarks/>
        Public Property cumw50() As Boolean
            Get
                Return Me.cumw50Field
            End Get
            Set
                Me.cumw50Field = value
                Me.RaisePropertyChanged("cumw50")
            End Set
        End Property
        
        '''<remarks/>
        Public Property cumw64() As Boolean
            Get
                Return Me.cumw64Field
            End Get
            Set
                Me.cumw64Field = value
                Me.RaisePropertyChanged("cumw64")
            End Set
        End Property
        
        '''<remarks/>
        Public Property critfireo() As Boolean
            Get
                Return Me.critfireoField
            End Get
            Set
                Me.critfireoField = value
                Me.RaisePropertyChanged("critfireo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property dryfireo() As Boolean
            Get
                Return Me.dryfireoField
            End Get
            Set
                Me.dryfireoField = value
                Me.RaisePropertyChanged("dryfireo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property conhazo() As Boolean
            Get
                Return Me.conhazoField
            End Get
            Set
                Me.conhazoField = value
                Me.RaisePropertyChanged("conhazo")
            End Set
        End Property
        
        '''<remarks/>
        Public Property ptornado() As Boolean
            Get
                Return Me.ptornadoField
            End Get
            Set
                Me.ptornadoField = value
                Me.RaisePropertyChanged("ptornado")
            End Set
        End Property
        
        '''<remarks/>
        Public Property phail() As Boolean
            Get
                Return Me.phailField
            End Get
            Set
                Me.phailField = value
                Me.RaisePropertyChanged("phail")
            End Set
        End Property
        
        '''<remarks/>
        Public Property ptstmwinds() As Boolean
            Get
                Return Me.ptstmwindsField
            End Get
            Set
                Me.ptstmwindsField = value
                Me.RaisePropertyChanged("ptstmwinds")
            End Set
        End Property
        
        '''<remarks/>
        Public Property pxtornado() As Boolean
            Get
                Return Me.pxtornadoField
            End Get
            Set
                Me.pxtornadoField = value
                Me.RaisePropertyChanged("pxtornado")
            End Set
        End Property
        
        '''<remarks/>
        Public Property pxhail() As Boolean
            Get
                Return Me.pxhailField
            End Get
            Set
                Me.pxhailField = value
                Me.RaisePropertyChanged("pxhail")
            End Set
        End Property
        
        '''<remarks/>
        Public Property pxtstmwinds() As Boolean
            Get
                Return Me.pxtstmwindsField
            End Get
            Set
                Me.pxtstmwindsField = value
                Me.RaisePropertyChanged("pxtstmwinds")
            End Set
        End Property
        
        '''<remarks/>
        Public Property ptotsvrtstm() As Boolean
            Get
                Return Me.ptotsvrtstmField
            End Get
            Set
                Me.ptotsvrtstmField = value
                Me.RaisePropertyChanged("ptotsvrtstm")
            End Set
        End Property
        
        '''<remarks/>
        Public Property pxtotsvrtstm() As Boolean
            Get
                Return Me.pxtotsvrtstmField
            End Get
            Set
                Me.pxtotsvrtstmField = value
                Me.RaisePropertyChanged("pxtotsvrtstm")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpabv14d() As Boolean
            Get
                Return Me.tmpabv14dField
            End Get
            Set
                Me.tmpabv14dField = value
                Me.RaisePropertyChanged("tmpabv14d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpblw14d() As Boolean
            Get
                Return Me.tmpblw14dField
            End Get
            Set
                Me.tmpblw14dField = value
                Me.RaisePropertyChanged("tmpblw14d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpabv30d() As Boolean
            Get
                Return Me.tmpabv30dField
            End Get
            Set
                Me.tmpabv30dField = value
                Me.RaisePropertyChanged("tmpabv30d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpblw30d() As Boolean
            Get
                Return Me.tmpblw30dField
            End Get
            Set
                Me.tmpblw30dField = value
                Me.RaisePropertyChanged("tmpblw30d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpabv90d() As Boolean
            Get
                Return Me.tmpabv90dField
            End Get
            Set
                Me.tmpabv90dField = value
                Me.RaisePropertyChanged("tmpabv90d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tmpblw90d() As Boolean
            Get
                Return Me.tmpblw90dField
            End Get
            Set
                Me.tmpblw90dField = value
                Me.RaisePropertyChanged("tmpblw90d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpabv14d() As Boolean
            Get
                Return Me.prcpabv14dField
            End Get
            Set
                Me.prcpabv14dField = value
                Me.RaisePropertyChanged("prcpabv14d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpblw14d() As Boolean
            Get
                Return Me.prcpblw14dField
            End Get
            Set
                Me.prcpblw14dField = value
                Me.RaisePropertyChanged("prcpblw14d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpabv30d() As Boolean
            Get
                Return Me.prcpabv30dField
            End Get
            Set
                Me.prcpabv30dField = value
                Me.RaisePropertyChanged("prcpabv30d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpblw30d() As Boolean
            Get
                Return Me.prcpblw30dField
            End Get
            Set
                Me.prcpblw30dField = value
                Me.RaisePropertyChanged("prcpblw30d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpabv90d() As Boolean
            Get
                Return Me.prcpabv90dField
            End Get
            Set
                Me.prcpabv90dField = value
                Me.RaisePropertyChanged("prcpabv90d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property prcpblw90d() As Boolean
            Get
                Return Me.prcpblw90dField
            End Get
            Set
                Me.prcpblw90dField = value
                Me.RaisePropertyChanged("prcpblw90d")
            End Set
        End Property
        
        '''<remarks/>
        Public Property precipa_r() As Boolean
            Get
                Return Me.precipa_rField
            End Get
            Set
                Me.precipa_rField = value
                Me.RaisePropertyChanged("precipa_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property sky_r() As Boolean
            Get
                Return Me.sky_rField
            End Get
            Set
                Me.sky_rField = value
                Me.RaisePropertyChanged("sky_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property td_r() As Boolean
            Get
                Return Me.td_rField
            End Get
            Set
                Me.td_rField = value
                Me.RaisePropertyChanged("td_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property temp_r() As Boolean
            Get
                Return Me.temp_rField
            End Get
            Set
                Me.temp_rField = value
                Me.RaisePropertyChanged("temp_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wdir_r() As Boolean
            Get
                Return Me.wdir_rField
            End Get
            Set
                Me.wdir_rField = value
                Me.RaisePropertyChanged("wdir_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wspd_r() As Boolean
            Get
                Return Me.wspd_rField
            End Get
            Set
                Me.wspd_rField = value
                Me.RaisePropertyChanged("wspd_r")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wwa() As Boolean
            Get
                Return Me.wwaField
            End Get
            Set
                Me.wwaField = value
                Me.RaisePropertyChanged("wwa")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tstmprb() As Boolean
            Get
                Return Me.tstmprbField
            End Get
            Set
                Me.tstmprbField = value
                Me.RaisePropertyChanged("tstmprb")
            End Set
        End Property
        
        '''<remarks/>
        Public Property tstmcat() As Boolean
            Get
                Return Me.tstmcatField
            End Get
            Set
                Me.tstmcatField = value
                Me.RaisePropertyChanged("tstmcat")
            End Set
        End Property
        
        '''<remarks/>
        Public Property wgust() As Boolean
            Get
                Return Me.wgustField
            End Get
            Set
                Me.wgustField = value
                Me.RaisePropertyChanged("wgust")
            End Set
        End Property
        
        '''<remarks/>
        Public Property iceaccum() As Boolean
            Get
                Return Me.iceaccumField
            End Get
            Set
                Me.iceaccumField = value
                Me.RaisePropertyChanged("iceaccum")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum formatType
        
        '''<remarks/>
        <System.Xml.Serialization.SoapEnumAttribute("24 hourly")>  _
        Item24hourly
        
        '''<remarks/>
        <System.Xml.Serialization.SoapEnumAttribute("12 hourly")>  _
        Item12hourly
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum featureTypeType
        
        '''<remarks/>
        Forecast_Gml2Point
        
        '''<remarks/>
        Forecast_Gml2AllWx
        
        '''<remarks/>
        Forecast_GmlsfPoint
        
        '''<remarks/>
        Forecast_GmlObs
        
        '''<remarks/>
        NdfdMultiPointCoverage
        
        '''<remarks/>
        Ndfd_KmlPoint
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum compTypeType
        
        '''<remarks/>
        IsEqual
        
        '''<remarks/>
        Between
        
        '''<remarks/>
        GreaterThan
        
        '''<remarks/>
        GreaterThanEqualTo
        
        '''<remarks/>
        LessThan
        
        '''<remarks/>
        LessThanEqualTo
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd")>  _
    Public Enum sectorType
        
        '''<remarks/>
        conus
        
        '''<remarks/>
        nhemi
        
        '''<remarks/>
        alaska
        
        '''<remarks/>
        guam
        
        '''<remarks/>
        hawaii
        
        '''<remarks/>
        puertori
        
        '''<remarks/>
        npacocn
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ndfdXMLPortTypeChannel
        Inherits ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ndfdXMLPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType)
        Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NDFDgen(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal product As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.productType, ByVal startTime As Date, ByVal endTime As Date, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.NDFDgen
            Return MyBase.Channel.NDFDgen(latitude, longitude, product, startTime, endTime, Unit, weatherParameters)
        End Function
        
        Public Function NDFDgenByDay(ByVal latitude As Decimal, ByVal longitude As Decimal, ByVal startDate As Date, ByVal numDays As String, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal format As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.formatType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.NDFDgenByDay
            Return MyBase.Channel.NDFDgenByDay(latitude, longitude, startDate, numDays, Unit, format)
        End Function
        
        Public Function NDFDgenLatLonList(ByVal listLatLon As String, ByVal product As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.productType, ByVal startTime As Date, ByVal endTime As Date, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.NDFDgenLatLonList
            Return MyBase.Channel.NDFDgenLatLonList(listLatLon, product, startTime, endTime, Unit, weatherParameters)
        End Function
        
        Public Function NDFDgenByDayLatLonList(ByVal listLatLon As String, ByVal startDate As Date, ByVal numDays As String, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal format As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.formatType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.NDFDgenByDayLatLonList
            Return MyBase.Channel.NDFDgenByDayLatLonList(listLatLon, startDate, numDays, Unit, format)
        End Function
        
        Public Function GmlLatLonList(ByVal listLatLon As String, ByVal requestedTime As Date, ByVal featureType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.featureTypeType, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal weatherParameters As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.weatherParametersType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.GmlLatLonList
            Return MyBase.Channel.GmlLatLonList(listLatLon, requestedTime, featureType, Unit, weatherParameters)
        End Function
        
        Public Function GmlTimeSeries(ByVal listLatLon As String, ByVal startTime As Date, ByVal endTime As Date, ByVal compType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.compTypeType, ByVal featureType As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.featureTypeType, ByVal Unit As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.unitType, ByVal propertyName As String) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.GmlTimeSeries
            Return MyBase.Channel.GmlTimeSeries(listLatLon, startTime, endTime, compType, featureType, Unit, propertyName)
        End Function
        
        Public Function LatLonListSubgrid(ByVal lowerLeftLatitude As Decimal, ByVal lowerLeftLongitude As Decimal, ByVal upperRightLatitude As Decimal, ByVal upperRightLongitude As Decimal, ByVal resolution As Decimal) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.LatLonListSubgrid
            Return MyBase.Channel.LatLonListSubgrid(lowerLeftLatitude, lowerLeftLongitude, upperRightLatitude, upperRightLongitude, resolution)
        End Function
        
        Public Function LatLonListLine(ByVal endPoint1Lat As Decimal, ByVal endPoint1Lon As Decimal, ByVal endPoint2Lat As Decimal, ByVal endPoint2Lon As Decimal) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.LatLonListLine
            Return MyBase.Channel.LatLonListLine(endPoint1Lat, endPoint1Lon, endPoint2Lat, endPoint2Lon)
        End Function
        
        Public Function LatLonListZipCode(ByVal zipCodeList As String) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.LatLonListZipCode
            Return MyBase.Channel.LatLonListZipCode(zipCodeList)
        End Function
        
        Public Function LatLonListSquare(ByVal centerPointLat As Decimal, ByVal centerPointLon As Decimal, ByVal distanceLat As Decimal, ByVal distanceLon As Decimal, ByVal resolution As Decimal) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.LatLonListSquare
            Return MyBase.Channel.LatLonListSquare(centerPointLat, centerPointLon, distanceLat, distanceLon, resolution)
        End Function
        
        Public Function CornerPoints(ByVal sector As ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.sectorType) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.CornerPoints
            Return MyBase.Channel.CornerPoints(sector)
        End Function
        
        Public Function LatLonListCityNames(ByVal displayLevel As String) As String Implements ReferencePost_4c22e180_cebd_4a5b_9d9f_5055469a7d94.ndfdXMLPortType.LatLonListCityNames
            Return MyBase.Channel.LatLonListCityNames(displayLevel)
        End Function
    End Class
End Namespace
